safe:        false
encoding:    "utf-8"
url:         http://localhost:4000/
baseurl:     

muster_version: 0.2.0
json4s_version: 3.2.10

source:      .
destination: ../../target/site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: rouge

markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink:   date

exclude     : ["Gemfile", "Gemfile.lock", "Rakefile"]
include     : ["*.jpg"]

title       : "Muster"
sub_title   : "Fast serialization for classes in scala"
rich_title  : "<strong>Muster</strong> by json4s"
rich_byline : "<strong>Fast serialization</strong> for classes in scala"
sponsor:
  byline    : "Maintained by"
  name      : "casualjim"
  url       : "https://github.com/casualjim"
  footer    : "This project is maintained by <a href=\"http://flanders.co.nz\">casualjim</a>"

ga_code     : "UA-240612-8"
github:
  username  : "json4s"
  project   : "muster"
